return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.18.2",
  orientation = "orthogonal",
  renderorder = "right-up",
  width = 156,
  height = 124,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 31,
  properties = {},
  tilesets = {
    {
      name = "Tile",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../images/tiles/Tile.png",
      imagewidth = 224,
      imageheight = 576,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 126,
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Collision",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["collidable"] = "1"
      },
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 544,
          width = 160,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 576,
          width = 672,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 544,
          width = 256,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 544,
          width = 576,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880.17,
          y = 1208.91,
          width = 1023.33,
          height = 111.347,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1845.17,
          y = 858.961,
          width = 668.081,
          height = 111.347,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1733.83,
          y = 196.182,
          width = 588.547,
          height = 95.4401,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 721.103,
          y = 360.551,
          width = 148.462,
          height = 58.3245,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2603.39,
          y = 694.592,
          width = 503.712,
          height = 90.1379,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2401.91,
          y = 429.48,
          width = 249.205,
          height = 95.4401,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2582.18,
          y = 1436.9,
          width = 911.983,
          height = 169.671,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 355.249,
          y = 1696.71,
          width = 885.472,
          height = 100.742,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2545.07,
          y = 2873.81,
          width = 1092.26,
          height = 164.369,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752.916,
          y = 2507.95,
          width = 1081.65,
          height = 190.88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10.6045,
          y = 2120.89,
          width = 1892.9,
          height = 143.16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 408.271,
          y = 3282.08,
          width = 1421,
          height = 132.556,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 90.1379,
          y = 2863.2,
          width = 710.498,
          height = 180.276,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3032.87,
          y = 2322.38,
          width = 742.312,
          height = 217.391,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2635.21,
          y = 1967.13,
          width = 1664.9,
          height = 164.369,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3324.5,
          y = 965.005,
          width = 959.703,
          height = 153.765,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 156,
      height = 124,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2UFug0AQRNEoJ8j9T5t9RGSTQNcM9Z7EzhKm+TYwfHwAAAAAV/u8YYPf6I1JegPgaVyXmKQ3+BvPFUzSG5P0Bvv5Otim93e071efe3djLUfXhavO9dF5f/ea5N3AM93x/uc/HV39vQCA9bnmM0lvTNIbAE3uXFOEn/TGJL2RtkNnd/xOVjtG1qE3pqRa01snvTFJbwDACpL3JO5L+uiNSXoDAACaeOZhkt6YYk2HSXpjkt4AgJW5T2GS3pikNwAAAFhb4j2qtYFe6T701iXdh966pPvQXJd0G3rrkm5jp97Sx7X7/M6aOJ6V55PuoK23dukO9NYl3YHeADr5L+cK7h2YpDcm6Y1JemOS3q515zyfMP+2471burH2+bdJN6a3PunO9NYl3ZneuqQ701uXq1vRGq/oAwAA9mc94rz0Os/O8zWP89Kd7Txf8zgv3dnO8zWP89Kd7Txfszgv3dkTZmwWeWYMAAAA3azHdEuvbeqtS7ofvXVJ96O3Lul+9AYAAAAAAAAAAADAU30Db3oU/w=="
    }
  }
}
